<div class="form col align-self-center">
  <form class="edit-password-form" name="editPasswordForm" method="post">
    <h3 class="form-heading">Reset Password</h3>

    <br>
    <input class="form-control is-invalid" id="password" type="password"  placeholder="password"/>
    <div id="password-feedback" class="invalid-feedback">Enter a password</div>

    <br>
    <input class="form-control is-invalid" id="repeat-password" type="password" placeholder="repeat password"/>
    <div id="repeat-password-feedback" class="invalid-feedback">Repeat Password</div>

    <br>
    <button type="submit" class="btn-success" name="edit_password">reset</button>
  </form>
</div>