<div class="form col align-self-center">
  <form class="forgot-password-form" name="forgotPasswordForm" method="post">
    <h3 class="form-heading">Forgot Password</h3>
    <input class="input" id="forgot-password-email" type="text" name="email" placeholder="email"/>
    <button type="submit" class="btn-success" name="resetPassword">reset password</button>

    <?php echo $this->data['error_message']; ?>
    
  </form>
</div>