<h3 class="form-heading">
    <?php echo $this->data["username"]; ?>
</h3>

<div class="profile-img">
    <img src="<?php echo $this->data['image']; ?>" alt="<?php echo $this->data['image']; ?>" width="200" height="200">
</div>

<br>
<br>

<form action="/profile/user/<?php echo $this->data["username"]; ?>" class="add-friend-form" name="addFriendForm" method="post">
    <?php

        if(!$this->data["pending"] && !$this->data["friends"])
            echo '<button type="submit" class="btn btn-sm add-friend-button" name="sendFriendRequest">Send ' . $this->data["username"] . ' a friend request</button>';
        else if($this->data["pending"] && !$this->data["friends"] && !$this->data['request_receiver'])
            echo '<button type="submit" class="btn btn-sm remove-friend-button" name="cancelFriendRequest">Cancel ' . $this->data["username"] . '\'s friend request</button>';
        else if($this->data["pending"] && !$this->data["friends"] && $this->data['request_receiver'])
            echo 'You have a pending request from ' . $this->data["username"];
        else
            echo '<button type="submit" class="btn btn-sm remove-friend-button" name="removeFriend">Remove ' . $this->data["username"] . '</button>';
    ?>
</form>