<h1 class="form-heading">Update My Account</h1>

<h5>
<?php 
  if(!empty($_GET['update_successful']) == true) {
    echo $_GET['field'] . ' successfully updated';
  }

  if(!empty($_GET['update_failed']) == true) {
    echo $_GET['field'] . ' was not updated<br>Current password was not correct';
  }
?>
</h5>

<div class="form col align-self-center">
  <form method="post" enctype="multipart/form-data">
    <h3 class="form-heading">Update Profile Image</h3>
    <h5 class="form-heading">Current Profile Image</h5>
    <div>
      <img src="<?php echo $this->data['profile_image']; ?>" alt="<?php echo $this->data['profile_image']; ?>" class="img-thumbnail mb-4"></img>
    </div>
    <div id="image_div"></div>
    <h5 id="file_error" class="text-warning"></h5>
    <input onchange="profileImagePreview(this)" class="btn" type="file" name="profile_image"></input>
    <div id="upload_btn_div"></div>
  </form>
</div>

<div class="form col align-self-center">
  <form id="edit-name-form" method="post">
    <h3 class="form-heading">Update Name</h3>

    <h6><?php echo $this->data['firstname'] . ' ' . $this->data['lastname']; ?> </h6>

    <br>
    <input class="form-control is-invalid" id="firstname" name="firstname" type="text" placeholder="new first name"/>
    <div id="firstname-feedback" class="invalid-feedback">Enter your first name</div>

    <br>
    <input class="form-control is-invalid" id="lastname" name="lastname" type="text" placeholder="new last name"/>
    <div id="lastname-feedback" class="invalid-feedback">Enter your last name</div>

    <br>
    <button type="submit" class="btn-success" name="edit-name">update</button>

  </form>
</div>

<div class="form col align-self-center">
  <form id="edit-username-form" method="post">
    <h3 class="form-heading">Update Username</h3>

    <h6><?php echo $this->data['username']; ?> </h6>

    <br>
    <input class="form-control is-invalid" id="edit-username" name="edit-username-text" type="text" placeholder="New username"/>
    <div id="username-feedback" class="invalid-feedback">Enter a username</div>

    <br>
    <button type="submit" class="btn-success" name="edit-username">update</button>
  </form>
</div>

<div class="form col align-self-center">
  <form name="edit-email-form" id="edit-email-form" method="post">
    <h3 class="form-heading">Update Email</h3>

    <h6><?php echo $this->data['email']; ?> </h6>

    <br>
    <input class="form-control is-invalid" id="edit-email" name="edit-email-text" type="text" placeholder="email"/>
    <div id="edit-email-feedback" class="invalid-feedback">Enter a valid Email</div>

    <br>
    <button type="submit" class="btn-success" name="edit-email">update</button>
  </form>
</div>

<div class="form col align-self-center">
  <form name="edit-password-form" id="edit-password-form" method="post">
    <h3 class="form-heading">Update Password</h3>

    <input class="form-control" id="current-account-password" name="current-account-password" type="password"  placeholder="current password"/>

    <br>
    <input class="form-control is-invalid" id="password" name="password" type="password"  placeholder="password"/>
    <div id="password-feedback" class="invalid-feedback">Enter a password</div>

    <br>
    <input class="form-control is-invalid" id="repeat-password" type="password" placeholder="repeat password"/>
    <div id="repeat-password-feedback" class="invalid-feedback">Repeat password</div>

    <br>
    <button type="submit" class="btn-success" name="edit_password">update</button>
  </form>
</div>