<div class="form col align-self-center">
  <form class="create-account-form" id="create-account-form" method="post">

    <h3 class="form-heading">Create Account</h3>

    <input class="form-control is-invalid" id="firstname" name="firstname" type="text" placeholder="first name"/>
    <div id="firstname-feedback" class="invalid-feedback">Enter your first name</div>

    <br>
    <input class="form-control is-invalid" id="lastname" name="lastname" type="text" placeholder="last name"/>
    <div id="lastname-feedback" class="invalid-feedback">Enter your last name</div>

    <br>
    <input class="form-control is-invalid" id="username" name="username" type="text" placeholder="username"/>
    <div id="username-feedback" class="invalid-feedback">Enter a username</div>

    <br>
    <input class="form-control is-invalid" id="email" name="email" type="text" placeholder="email"/>
    <div id="email-feedback" class="invalid-feedback">Enter a valid Email</div>
    
    <br>
    <input class="form-control is-invalid" id="password" name="password" type="password"  placeholder="password"/>
    <div id="password-feedback" class="invalid-feedback">Enter a password</div>

    <br>
    <input class="form-control is-invalid" id="repeat-password" name="repeat-password" type="password" placeholder="repeat password"/>
    <div id="repeat-password-feedback" class="invalid-feedback">Repeat Password</div>

    <br>
    <button type="submit" class="create-account-button" name="create-account">sign me up</button>
  </form>
</div>