<h1 class="form-heading">Disclaimer</h1>

<h2 align="left">Risks you assume by entering our site</h2>

<div align="left">
By entering the LiveChat website, you release the LiveChat creator, from all liability for claims, losses, expenses, damages and costs you incur as a result of relying on the information on this site. This includes liability relating to:<br><br>

 - defamatory material on any database<br>
 - dealings with work (including software) in which you hold copyright or other intellectual property right<br><br>
 
You take on all risks of using the site, including risks to your computer, software or data.<br><br>

Third party material that we include on this site, doesn’t necessarily reflect our views.
</div>

<br><br><h2 align="left">Web chat</h2>

<div align="left">
Any information we collect through Web chat meets our privacy statement.
</div>

<br><br><h2 align="left">Websites we link to</h2>

<div align="left">
LiveChat has no direct control over linked website content or changes to their content.<br><br>

We link to external websites in good faith, but it’s your responsibility to decide on their accuracy, currency, reliability and correctness.<br><br>

When we link to external websites and any applications they use (such as Twitter, Facebook, LinkedIn, Wordpress and YouTube) we aren’t endorsing or recommending any related material, products or services. You are responsible for being aware of the organisation hosting websites you visit.
</div>