</div>
</div>

<!-- Footer -->
<footer class="footer font-small bg-dark text-white">
    <!-- Footer Links -->
    <div class="container text-center text-md-left">
        <!-- Grid row -->
        <div class="row">
            <!-- Grid column -->
            <div class="col-md-4 mx-auto">
                <!-- Content -->
                <h5 class="font-weight-bold mt-3 mb-4">LiveChat</h5>
                <p>Chat with friends, anytime, anywhere.</p>

                <ion-icon onclick="toggleViewMode()" id="viewMode" class="btn btn-secondary d-flex" name="moon-outline" size="small"></ion-icon>
                
            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-2 mx-auto">
                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Legal</h5>

                <ul class="list-unstyled">
                    <li><a href="/disclaimer">Disclaimer</a></li>
                    <li><a href="/disclaimer">Terms of Use</a></li>
                </ul>
            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-2 mx-auto">
                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Help</h5>

                <ul class="list-unstyled">
                    <li><a href="/aboutUs">About Us</a></li>
                    <li><a href="/contactUs">Contact Us</a></li>
                </ul>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->        
    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">
        © 2020 Copyright <a href="https://rowenprogrammer.wordpress.com/"> Rowen Govender </a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->
<!-- My JQuery scripts -->
<script type="text/javascript" language="javascript" src="\javascripts\cookie.js"></script>
<script type="text/javascript" language="javascript" src="\javascripts\header.js"></script>
<script type="text/javascript" language="javascript" src="\javascripts\viewmode.js"></script>
<script type="text/javascript" language="javascript" src="\javascripts\validation.js"></script>
<script type="text/javascript" language="javascript" src="\javascripts\edit-account-validation.js"></script>
<script type="text/javascript" language="javascript" src="\javascripts\profile-image.js"></script>
<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<!-- Ionicons -->
<script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>
</body>
</html>