<div class="form col align-self-center">
  <form class="forgot-password-form" id="forgot-password-form" method="post">
    <h3 class="form-heading">Forgot Password</h3>

    <h6><?php echo $this->data['error_message']; ?></h6>

    <br>
    <input class="form-control is-invalid" id="forgot-password-email" name="forgot-password-email" type="text" placeholder="Email"/>
    <div id="forgot-password-email-feedback" class="invalid-feedback">Enter your email</div>

    <br>
    <button type="submit" class="btn-success" name="edit-password">reset</button>
    
  </form>
</div>