<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link href="\css\style.css" rel="stylesheet">
    <!-- jQuery Lib -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"  crossorigin="anonymous"></script>
    <title>LiveChat</title>

</head>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark text-white">
    <a class="navbar-brand" href="/home">LiveChat</a>
    <form class="d-flex ml-auto" method="POST">
        <div class="p-2 bd-highlight" id="search-bar"></div>
        <div class="p-2 bd-highlight" id="accountBtn"></div>
        <div class="p-2 bd-highlight" id="loginBtn"></div>
    </form>
</nav>
<!-- Navbar -->

<body>
    <div class="container content">
        <div class="row justify-content-md-center"></div>
