<h4 class="form-heading">
    <?php  
        echo '<div class="main-image-cropper justify-content-center">' .
        '<img class="main-profile-pic" src="' . $this->data['profile_img'] . '" alt="' . $this->data['profile_img']  .' width="400" height="400"">' . 
        '</div><br>' .
        $this->data['username'];

        if($this->data["admin"]) {
            echo ' - Admin Account';
        }
    ?> 
</h4>

<div class="row profile-row mx-1">
    <div class="friends-list col-3 px-1">
        <h5>Friends <ion-icon name="people-circle-outline"></ion-icon></h5>
        <ul class="list-group">
            <?php
                if(!empty($this->data["requests"])) {

                    foreach($this->data["requests"] as $requester)

                    echo '<form class="list-group-item" method="post">' .
                        '<a href="/profile/user/' . $requester['name'] . '" class="link-unstyled">' .
                        '<h6>Request Pending</h6>' .
                        '<span class="image-cropper profile-img">' .
                        '<img class="profile-pic" src="' . $requester['image']  . '" alt="' . $requester['image']  .' width="50" height="50">' .
                        '</span>' .
                        '<span class="profile-username">' . $requester['name'] . '</span>' .
                        '</a>' .
                        '<br><br>' .
                        '<button name="declineBtn" class="request-btn btn btn-sm btn-danger ml-2" type="submit" value="' . $requester['id'] .'">Decline</button>' .
                        '<button name="acceptBtn" class="request-btn btn btn-sm btn-success" type="sumbit" value="' . $requester['id'] . '">Accept</button>' .
                        '</form>';
                }

                if(!empty($this->data["friends"])) {

                    foreach($this->data["friends"] as $friend) {

                        echo '<li class="list-group-item">' .
                        '<a href="/profile/user/' . $friend['name'] . '" class="link-unstyled">' .
                        '<span class="image-cropper profile-img">' .
                        '<img class="profile-pic" src="' . $friend['image']  . '" alt="' . $friend['image']  .' width="50" height="50">' .
                        '</span>' .
                        '<span class="profile-username">' .
                        $friend['name'] .
                        '</span>' .
                        '</a>' .
                        '</li>';
                    }
                }
                else {

                    echo '<li class="list-group-item">Chatting is best enjoyed with friends</li>';
                }
            ?>
        </ul>
    </div>
    <div class="active-chats-list col-2 px-1">
        <h5>Active Chats <ion-icon name="chatbubbles-outline"></ion-icon></h5>
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row justify-content-center">
                    <button type="button" class="btn btn-sm btn-primary" onClick="location.href='/account'">Create New Chat</button>
                </div>
            </li>

            <?php
                if(!empty($this->data["active_chat"])) {
                    
                    foreach($this->data["active_chats"] as $activeChat) {

                        echo '<li class="list-group-item">' . $activeChat['name'] . '</li>';
                    }
                }
                else {

                    echo '<li class="list-group-item">No active chats</li>';
                }
            ?>
        </ul>
    </div>
    <div class="col-5 px-1">
        <h5>Chat <ion-icon name="chatbubble-ellipses-outline"></ion-icon></h5>
        <div class="chat">
            Beginning of chat.
        </div>
        <div class="chat">
            <form class="row mx-0">
                <div class="col-10 mt-1 px-1">
                    <textarea class="form-control" rows="3" placeholder="Remember, be nice and have fun!"></textarea>
                </div>
                <div class="col-2 mt-1 px-1">
                    <button class="message-btn btn">Send</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-2 px-1">
        <h5>Lobby Members</ion-icon></h5>
        <ul class="members-list">
        <?php
            if(!empty($this->data["lobby_members"])) {

                foreach($this->data["lobby_members"] as $lobby_member) {

                    echo '<li class="members-list-item">' . $lobby_member['username'] . '</li>';
                }
            }
            else {
                echo '<li class="members-list-item">' . 'No members here' . '</li>';
            }
        ?>

        </ul>
    </div>
</div>
You've reached the end of the chat