<h4 class="form-heading">
    <?php  
        echo '<div class="main-image-cropper justify-content-center">' .
        '<img class="main-profile-pic" src="' . $this->data['profile_img'] . '" alt="' . $this->data['profile_img']  .' width="400" height="400"">' . 
        '</div><br>' .
        $this->data['username'];

        if($this->data["admin"]) {
            echo ' - Admin Account';
        }
    ?> 
</h4>

<div class="row profile-row mx-1">
    <div class="friends-list col-3 px-1">
        <h5>Friends <ion-icon name="people-circle-outline"></ion-icon></h5>
        <ul class="list-group">
            <?php
                if(!empty($this->data["requests"])) {

                    foreach($this->data["requests"] as $requester)

                        echo '<form class="list-group-item" method="post">' .
                        '<a href="/profile/user/' . $requester['name'] . '" class="link-unstyled">' .
                        '<h6>Request Pending</h6>' .
                        '<span class="image-cropper profile-img">' .
                        '<img class="profile-pic" src="' . $requester['image']  . '" alt="' . $requester['image']  .' width="50" height="50">' .
                        '</span>' .
                        '<span class="profile-username">' . $requester['name'] . '</span>' .
                        '</a>' .
                        '<br><br>' .
                        '<button name="declineBtn" class="request-btn btn btn-sm btn-danger ml-2" type="submit" value="' . $requester['id'] .'">Decline</button>' .
                        '<button name="acceptBtn" class="request-btn btn btn-sm btn-success" type="sumbit" value="' . $requester['id'] . '">Accept</button>' .
                        '</form>';
                }

                if(!empty($this->data["friends"])) {

                    foreach($this->data["friends"] as $friend) {

                        echo '<li class="list-group-item">' .
                        '<a href="/profile/user/' . $friend['name'] . '" class="link-unstyled">' .
                        '<span class="image-cropper profile-img">' .
                        '<img class="profile-pic" src="' . $friend['image']  . '" alt="' . $friend['image']  .' width="50" height="50">' .
                        '</span>' .
                        '<span class="profile-username">' .
                        $friend['name'] .
                        '</span>' .
                        '</a>' .
                        '</li>';
                    }
                }
                else {

                    echo '<li class="list-group-item">Chatting is best enjoyed with friends</li>';
                }
            ?>
        </ul>
    </div>
    <div class="active-chats-list col-2 px-1">
        <h5>Active Chats<ion-icon name="chatbubbles-outline"></ion-icon></h5>
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row justify-content-center">
                    <form method="post" class="row justify-content-center">
                        <input class="chat-name-input" type="text" name="chat-group-name" placeholder="Chat Name"></input>
                        <button type="submit" class="btn btn-sm btn-primary" name="create-chat-button">Create New Chat</button>
                    </form>
                </div>
            </li>

            <?php
                if(!empty($this->data["active_chats"])) {

                    $chat_group = new ChatGroup('ChatGroup', '');
                    
                    foreach($this->data["active_chats"] as $activeChat) {

                        echo '<button class="chat-group-btn" id="chat-group-btn" name="chat-group-btn" value="' . $activeChat['group_id'] . '">' . $chat_group->getChatGroup($activeChat['group_id'])[0]['chat_name'] . '</button>';
                    }
                }
                else {

                    echo '<li class="list-group-item">No active chats</li>';
                }
            ?>
        </ul>
    </div>
    <div class="col-5 px-1">
        <h5>Chat <ion-icon name="chatbubble-ellipses-outline"></ion-icon></h5>

        <div class="chat" id="chat-window">
        <?php 
            echo 'Open a lobby and start chatting' .
            '</div>';
        ?>

        <div class="" id="message-box">

        </div>

    </div>
    <div class="col-2 px-1">
        <h5>Lobby Members</ion-icon></h5>
        <ul class="members-list" id="lobby-members-list">
        <?php
            echo '<li class="members-list-item">' . 'No members here' . '</li>';
        ?>

        </ul>
    </div>
</div>
You've reached the end of the chat


<script>
    $('button[id="chat-group-btn"]').click(function() {

        var id = this.value;

        $.ajax ({
            url: "/home/index/?group_chat="+ encodeURIComponent(this.value),
            success: function(result) {

                var chat_window = '';

                var obj = JSON.parse(result)['chat-window'];
                var obj2 = JSON.parse(result)['lobby-list'];

                var lobby_members = '';

                if(obj != null) {

                    obj.forEach(myFunction);

                    function myFunction(item, index) {
                        
                        chat_window += '<div class="username">' +
                        '<b>' +  item.username + '</b>' +
                        '</div>' +
                        item.message +
                        '<div class="date-time-info">' +
                        item.posted +
                        '</div>' +
                        '<hr>'
                    }

                    $("#chat-window").html(chat_window);
                }
                else {
                    $("#chat-window").html('There are no messages yet!');
                }

                $("#message-box").attr('class', 'message-box');

                $("#message-box").html (
                    '<form id="message-form" method="post" class="row mx-0">' +
                    '<div class="col-10 mt-1 px-1">' +
                    '<textarea class="form-control" name="message" rows="3" placeholder="Remember, be nice and have fun!"></textarea>' +
                    '</div>' +
                    '<div class="col-2 mt-1 px-1">' +
                    '<button type="submit" name="send-message-button" id="send-message-button" value="" class="message-btn btn">Send</button>' +
                    '</div>' +
                    '</form>'
                );

                $('#message-form').submit(function(event) {
                    
                    var formData = {
                        "chat_id" : $('button[name=send-message-button]').val(),
                        "message" : $('textarea[name=message]').val()
                    }

                    $.ajax({
                        type : 'post',
                        url : '/home/index/?message_form=' + JSON.stringify(formData)
                    }).done(function(data) {

                        var json_data = JSON.parse(data);

                        $('textarea[name=message]').val('');

                        $("#chat-window").html(
                            chat_window += '<div class="username">' +
                            '<b>' +  json_data['username'] + '</b>' +
                            '</div>' +
                            json_data['message'] +
                            '<div class="date-time-info">' +
                            json_data['posted'] +
                            '</div>' +
                            '<hr>'                            
                        );
                    });

                    event.preventDefault();
                });

                $("#send-message-button").attr('value', id);

                obj2.forEach(myFunction2);

                    function myFunction2(item, index) {

                        lobby_members += 
                        '<li class="members-list-item">' +
                        item.username +
                        '</li>'
                    }

                    $("#lobby-members-list").html(lobby_members);
                }
            });
        });
</script>

