<h4><?php
  if(!empty($_GET['account-created']) == 1)
    echo 'Thanks for Joining! Login and start chatting';
?></h4>

<div class="form col align-self-center">
  <form class="login-form" name="loginForm" method="post">
    <h3 class="form-heading">Login</h3>
    <input class="input" id="login-email" type="text" name="email" placeholder="email"/>
    <input class="input" id="login-password" type="password" name="password" placeholder="password"/>
    <button type="submit" class="login-form-button" name="login">Login</button>
  </form>

  <a href="/forgotPassword" class="text-warning">forgot password</a>
</div>